unbind r
bind r source-file ~/.tmux.conf


# reset leader key from C-b to C-a
# set -g prefix C-a

set -g mouse on 
set -g default-terminal "tmux-256color"
set -g default-shell /bin/zsh

# set -g default-command "reattach-to-user-namespace -l $SHELL"

# starting windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1
set -g mode-keys vi

# vim like 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

#list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

# auto save and restore sessions with tmux-continuum/resurrect
set -g @continuum-save-interval '5'
set -g @continuum-boot 'on'
# init tmux plugin manager (keep this at the bottom of config)
run '~/.tmux/plugins/tpm/tpm'

# resurrect automatically
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
